import { createSeedAnalyticsStore, dateRangeForPreset, downloadReportCsv, buildAnalyticsReport, buildInternalAnalyticsAggregate, type AnalyticsExportKind, type AnalyticsReport, type InternalAnalyticsAggregate } from './analytics';
import type { AnalyticsDateRange, AnalyticsStore } from './analytics/types';

const dashboardStyles = `
:root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, sans-serif; color: #1d2925; background: #f3f5f1; }
* { box-sizing: border-box; } body { margin: 0; } button, select, input { font: inherit; }
.analytics-app { min-height: 100vh; } .analytics-shell { width: min(1240px, calc(100% - 40px)); margin: 0 auto; padding: 34px 0 70px; }
.analytics-header { display: flex; justify-content: space-between; align-items: flex-end; gap: 24px; margin-bottom: 28px; } .analytics-kicker { margin: 0 0 8px; color: #66806c; font-size: 11px; font-weight: 800; letter-spacing: .15em; text-transform: uppercase; } h1, h2, h3, p { margin-top: 0; } h1 { margin-bottom: 10px; font: 500 clamp(2.5rem, 6vw, 4.6rem)/.94 Georgia, serif; letter-spacing: -.065em; } .analytics-header p { max-width: 620px; margin-bottom: 0; color: #66736b; line-height: 1.55; }
.analytics-controls { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 8px; } .analytics-controls select, .analytics-controls input, .export-button { min-height: 38px; padding: 0 11px; border: 1px solid #d5ded5; border-radius: 10px; color: #344339; background: #fff; font-size: 12px; } .range-button, .export-button { border: 0; cursor: pointer; } .range-button { padding: 10px 12px; border-radius: 9px; color: #66736b; background: #e7ede7; font-size: 12px; } .range-button.active { color: #fff; background: #315b44; }
.metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 12px; } .metric-card, .analytics-panel { border: 1px solid #dce4dc; border-radius: 16px; background: rgba(255,255,255,.8); box-shadow: 0 12px 32px rgba(29,52,37,.045); } .metric-card { padding: 19px; } .metric-label { margin-bottom: 13px; color: #748177; font-size: 11px; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; } .metric-value { margin: 0; color: #1f3828; font: 500 2.1rem/1 Georgia, serif; } .metric-note { margin: 8px 0 0; color: #819087; font-size: 11px; }
.analytics-grid { display: grid; grid-template-columns: 1.15fr .85fr; gap: 12px; margin-bottom: 12px; } .analytics-panel { padding: 22px; } .analytics-panel h2 { margin-bottom: 5px; font: 500 1.6rem/1.05 Georgia, serif; letter-spacing: -.04em; } .panel-copy { margin-bottom: 18px; color: #7a877e; font-size: 12px; line-height: 1.5; }
.funnel-row { display: grid; grid-template-columns: 118px 1fr 48px; align-items: center; gap: 10px; margin: 12px 0; font-size: 12px; } .bar-track { height: 9px; overflow: hidden; border-radius: 20px; background: #e8eee8; } .bar-value { height: 100%; border-radius: inherit; background: #6d9274; } .funnel-row strong { text-align: right; color: #315b44; font-size: 12px; }
.chart-bars { display: grid; align-items: end; grid-template-columns: repeat(auto-fit, minmax(24px, 1fr)); gap: 7px; min-height: 150px; padding-top: 8px; border-bottom: 1px solid #dce4dc; } .day-bar { display: grid; grid-template-rows: 1fr auto; gap: 7px; min-width: 0; height: 140px; } .day-bar-fill { align-self: end; min-height: 3px; border-radius: 6px 6px 0 0; background: #6d9274; } .day-bar span { overflow: hidden; color: #849087; font-size: 9px; text-align: center; text-overflow: ellipsis; white-space: nowrap; }
.table-wrap { overflow-x: auto; } table { width: 100%; border-collapse: collapse; font-size: 12px; } caption { padding: 0 0 10px; color: #7b897f; font-size: 11px; text-align: left; } th, td { padding: 10px 8px; border-bottom: 1px solid #edf1ed; text-align: left; vertical-align: top; } th { color: #76857a; font-size: 10px; letter-spacing: .08em; text-transform: uppercase; } td strong { display: block; color: #284533; font-weight: 700; } td small { color: #8a958d; }
.insight { padding: 13px 14px; border-left: 3px solid #c69b45; border-radius: 4px; color: #56665a; background: #f6f1e6; font-size: 12px; line-height: 1.5; } .insight + .insight { margin-top: 8px; } .export-row { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 16px; } .export-button { color: #315b44; background: #e8f0e8; font-weight: 700; }
.empty-dashboard { padding: 80px 20px; text-align: center; } .muted { color: #87938a; }
@media (max-width: 860px) { .analytics-header { align-items: flex-start; flex-direction: column; } .analytics-controls { justify-content: flex-start; } .metric-grid { grid-template-columns: repeat(2, 1fr); } .analytics-grid { grid-template-columns: 1fr; } }
@media (max-width: 520px) { .analytics-shell { width: min(100% - 24px, 1240px); padding-top: 22px; } .metric-grid { grid-template-columns: 1fr 1fr; gap: 8px; } .metric-card { padding: 14px; } .metric-value { font-size: 1.65rem; } .funnel-row { grid-template-columns: 92px 1fr 38px; } }
`;

function escape(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character); }
function number(value: number): string { return new Intl.NumberFormat('en-GB').format(value); }
function pct(value: number): string { return `${value.toFixed(1)}%`; }
function table(headers: string[], rows: string[][], caption: string): string { return `<div class="table-wrap"><table><caption>${escape(caption)}</caption><thead><tr>${headers.map((header) => `<th scope="col">${escape(header)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join('')}</tr>`).join('') : '<tr><td colspan="8" class="muted">No data for this range.</td></tr>'}</tbody></table></div>`; }

function reportMarkup(report: AnalyticsReport, range: AnalyticsDateRange, admin: boolean, internal?: InternalAnalyticsAggregate): string {
  const maxDay = Math.max(1, ...report.daily.map((day) => day.impressions));
  const maxInterest = Math.max(1, ...report.topInterests.map((item) => item.count));
  const articleRows = (items: AnalyticsReport['topRecommendedArticles']) => items.map((item) => [`<strong>${escape(item.title)}</strong><small>${escape(item.articleId)}</small>`, escape(item.category), number(item.impressions), number(item.clicks), pct(item.ctr)]);
  const positionRows = report.positionPerformance.map((item) => [String(item.position), number(item.impressions), number(item.clicks), pct(item.ctr)]);
  const rankingRows = report.rankingModes.map((item) => [escape(item.mode), number(item.searches), number(item.clicks), pct(item.ctr)]);
  return `<div class="analytics-app"><style>${dashboardStyles}</style><main class="analytics-shell">
    <header class="analytics-header"><div><p class="analytics-kicker">Publisher intelligence · ${escape(report.publisherId)}</p><h1>Discovery, measured.</h1><p>Understand how readers move from curiosity to a story worth opening. Metrics are scoped to this publisher and show factual performance rather than unsupported ranking claims.</p></div><div class="analytics-controls"><label><span class="muted">Publisher</span> <select data-control="publisher"><option value="demo" ${report.publisherId === 'demo' ? 'selected' : ''}>Demo Publisher</option><option value="real-publisher" ${report.publisherId === 'real-publisher' ? 'selected' : ''}>Real Publisher</option></select></label><div role="group" aria-label="Date range"><button class="range-button" data-range="today">Today</button><button class="range-button" data-range="7d">7 days</button><button class="range-button active" data-range="30d">30 days</button></div><label><span class="muted">From</span> <input type="date" data-control="from"></label><label><span class="muted">To</span> <input type="date" data-control="to"></label></div></header>
    <section class="metric-grid" aria-label="Overview metrics">${[['Widget impressions', report.overview.widgetImpressions, 'readers who saw the launcher'], ['Widget opens', report.overview.widgetOpens, `${pct(report.overview.openToSearchRate)} open-to-search`], ['Searches completed', report.overview.searchesCompleted, `${number(report.overview.averageRecommendationsShown)} average recommendations`], ['Article clicks', report.overview.articleClicks, `${pct(report.overview.searchToClickRate)} search-to-click`]].map(([label, value, note]) => `<article class="metric-card"><div class="metric-label">${escape(String(label))}</div><p class="metric-value">${number(Number(value))}</p><p class="metric-note">${escape(String(note))}</p></article>`).join('')}</section>
    <div class="analytics-grid"><section class="analytics-panel"><h2>Engagement funnel</h2><p class="panel-copy">Unique sessions at each step. A session can appear in more than one step.</p>${report.funnel.map((item, index) => `<div class="funnel-row"><span>${escape(item.stage)}</span><div class="bar-track"><div class="bar-value" style="width:${item.percentage}%"></div></div><strong>${number(item.count)}</strong></div>`).join('')}</section><section class="analytics-panel"><h2>Usage over time</h2><p class="panel-copy">Daily widget impressions in the selected UTC range.</p><div class="chart-bars" role="img" aria-label="Daily widget impressions chart">${report.daily.map((day) => `<div class="day-bar" title="${escape(day.date)}: ${day.impressions} impressions"><div class="day-bar-fill" style="height:${Math.max(3, day.impressions / maxDay * 100)}%"></div><span>${escape(day.date.slice(5))}</span></div>`).join('')}</div></section></div>
    <div class="analytics-grid"><section class="analytics-panel"><h2>Top interests</h2><p class="panel-copy">Structured option IDs only. Free-text responses are represented as usage, never raw text.</p>${report.topInterests.slice(0, 6).map((item) => `<div class="funnel-row"><span>${escape(item.label)}</span><div class="bar-track"><div class="bar-value" style="width:${item.count / maxInterest * 100}%"></div></div><strong>${pct(item.percentage)}</strong></div>`).join('') || '<p class="muted">No structured interests yet.</p>'}</section><section class="analytics-panel"><h2>Reader personas</h2><p class="panel-copy">Configured role/persona selections.</p>${table(['Persona', 'Answers', 'Share'], report.topPersonas.map((item) => [escape(item.label), number(item.count), pct(item.percentage)]), 'Top reader personas')}</section></div>
    <section class="analytics-panel" style="margin-bottom:12px"><h2>Recommendation performance</h2><p class="panel-copy">Position-level measurements help distinguish visibility from click-through.</p>${table(['Position', 'Impressions', 'Clicks', 'CTR'], positionRows, 'Performance by recommendation position')}${table(['Ranking mode', 'Searches', 'Clicks', 'CTR'], rankingRows, 'Deterministic and hybrid measurements')}</section>
    <div class="analytics-grid"><section class="analytics-panel"><h2>Top recommended articles</h2>${table(['Article', 'Category', 'Impressions', 'Clicks', 'CTR'], articleRows(report.topRecommendedArticles), 'Articles shown most often')}${table(['Article', 'Category', 'Impressions', 'Clicks', 'CTR'], articleRows(report.topClickedArticles), 'Articles receiving the most clicks')}</section><section class="analytics-panel"><h2>Potential content gaps</h2><p class="panel-copy">Evidence-based opportunities, not definitive editorial instructions.</p>${report.contentGaps.length ? report.contentGaps.map((gap) => `<div class="insight"><strong>${escape(gap.interest)}</strong><br>${escape(gap.statement)} Click rate: ${pct(gap.clickRate)}.</div>`).join('') : '<p class="muted">No potential gaps identified in this range.</p>'}<h2 style="margin-top:26px">Archive content renewed</h2>${report.archiveInsights.length ? report.archiveInsights.slice(0, 3).map((item) => `<div class="insight"><strong>${escape(item.title)}</strong><br>${number(item.clicks)} clicks from recommendation impressions.</div>`).join('') : '<p class="muted">No older articles with clicks in this range.</p>'}</section></div>
    <section class="analytics-panel"><h2>Session metrics & exports</h2><p class="panel-copy">Sessions are ephemeral product analytics identifiers, not fingerprints or cross-site identities.</p><p class="muted">${number(report.sessions.total)} sessions · ${number(report.sessions.resultsViewed)} viewed results · ${number(report.sessions.articlesClicked)} clicked an article · ${number(report.sessions.answersChanged)} changed answers · ${number(report.sessions.restarted)} restarted</p><div class="export-row"><button class="export-button" data-export="daily">Export daily metrics</button><button class="export-button" data-export="interests">Export interests</button><button class="export-button" data-export="recommended">Export recommended articles</button><button class="export-button" data-export="clicked">Export clicked articles</button></div></section>
    ${admin && internal ? `<section class="analytics-panel" style="margin-top:12px"><h2>Internal view</h2><p class="panel-copy">Cross-publisher aggregates are available only in explicit development/admin mode and are not part of publisher-scoped views.</p><p class="muted">${number(internal.publisherCount)} publishers · ${number(internal.totalSearches)} searches · ${number(internal.totalClicks)} clicks · ${pct(internal.averageCtr)} aggregate CTR</p></section>` : ''}
  </main></div>`;
}

export async function renderAnalyticsDashboard(root: HTMLElement, store?: AnalyticsStore): Promise<void> {
  const analyticsStore = store ?? await createSeedAnalyticsStore();
  let publisherId = new URLSearchParams(window.location.search).get('publisher') ?? 'demo';
  let range = dateRangeForPreset('30d', new Date('2026-09-28T12:00:00.000Z'));
  const admin = new URLSearchParams(window.location.search).get('admin') === '1';
  const render = async () => {
    const events = await analyticsStore.query({ publisherId, range });
    const report = buildAnalyticsReport(events, publisherId, range);
    let internal: InternalAnalyticsAggregate | undefined;
    if (admin) {
      const ids = await analyticsStore.listPublisherIds();
      const reports = await Promise.all(ids.map(async (id) => buildAnalyticsReport(await analyticsStore.query({ publisherId: id, range }), id, range)));
      internal = buildInternalAnalyticsAggregate(reports);
    }
    root.innerHTML = reportMarkup(report, range, admin, internal);
    root.querySelector<HTMLSelectElement>('[data-control="publisher"]')?.addEventListener('change', (event) => { publisherId = (event.target as HTMLSelectElement).value; void render(); });
    root.querySelectorAll<HTMLButtonElement>('[data-range]').forEach((button) => button.addEventListener('click', () => { range = dateRangeForPreset(button.dataset.range as 'today' | '7d' | '30d', new Date('2026-09-28T12:00:00.000Z')); void render(); }));
    root.querySelectorAll<HTMLButtonElement>('[data-export]').forEach((button) => button.addEventListener('click', () => downloadReportCsv(report, button.dataset.export as AnalyticsExportKind)));
    root.querySelector<HTMLInputElement>('[data-control="from"]')?.addEventListener('change', (event) => { const value = (event.target as HTMLInputElement).value; if (value) { range = { ...range, from: `${value}T00:00:00.000Z` }; void render(); } });
    root.querySelector<HTMLInputElement>('[data-control="to"]')?.addEventListener('change', (event) => { const value = (event.target as HTMLInputElement).value; if (value) { range = { ...range, to: `${value}T23:59:59.999Z` }; void render(); } });
  };
  await render();
}
