import { createSeedAnalyticsStore, dateRangeForPreset, downloadReportCsv, buildAnalyticsReport, buildInternalAnalyticsAggregate, type AnalyticsExportKind, type AnalyticsReport, type InternalAnalyticsAggregate } from './analytics';
import type { AnalyticsDateRange, AnalyticsStore } from './analytics/types';
import { createPublisherRegistry } from './publishers/registry';

const dashboardStyles = `
:root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17213d;background:#f4f6fa}
*{box-sizing:border-box}body{margin:0}button,select,input{font:inherit}
.analytics-app{min-height:100vh;background:#f4f6fa}.analytics-shell{width:min(1340px,calc(100% - 48px));margin:0 auto;padding:28px 0 72px}
.dashboard-header{margin-bottom:22px}.publisher-line{display:flex;align-items:center;gap:9px;color:#5c6883;font-size:12px;font-weight:700;letter-spacing:.02em}.publisher-mark{display:grid;place-items:center;width:26px;height:26px;border-radius:9px;color:#fff;background:#3d4fb6;font-size:11px;font-weight:800}.dashboard-header-row{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-top:17px}.dashboard-eyebrow{margin:0 0 7px;color:#6371c7;font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.dashboard-header h1{margin:0;color:#111a35;font-size:clamp(1.9rem,3vw,2.65rem);font-weight:720;letter-spacing:-.045em;line-height:1.05}.dashboard-subtitle{max-width:640px;margin:9px 0 0;color:#68748d;font-size:13px;line-height:1.5}.dashboard-controls{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:8px}.dashboard-controls select,.dashboard-controls input,.dashboard-controls button{min-height:36px;border:1px solid #dbe0ed;border-radius:10px;color:#263252;background:#fff;font-size:12px}.dashboard-controls select,.dashboard-controls input{padding:0 10px}.dashboard-controls button{padding:0 11px;cursor:pointer}.dashboard-controls button:hover,.dashboard-controls button:focus-visible{border-color:#6d7cdb;outline:3px solid rgba(88,104,201,.16)}.range-button.active{border-color:#4b5cc1;color:#fff;background:#4b5cc1}.refresh-button{font-weight:700}.range-group{display:flex;gap:4px;padding:3px;border:1px solid #dbe0ed;border-radius:12px;background:#eef1f7}.range-group button{min-height:28px;border:0;background:transparent}.range-group button.active{background:#4b5cc1}.updated-label{margin:12px 0 0;color:#8791a5;font-size:11px}
.metric-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:14px}.metric-card,.analytics-panel{border:1px solid #dde2ec;border-radius:15px;background:#fff;box-shadow:0 10px 28px rgba(30,42,75,.045)}.metric-card{min-height:112px;padding:16px}.metric-label{color:#737e95;font-size:10px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.metric-value{margin:12px 0 5px;color:#141f40;font-size:1.85rem;font-weight:720;letter-spacing:-.045em}.metric-note{margin:0;color:#8a93a6;font-size:11px;line-height:1.35}
.layout-two{display:grid;grid-template-columns:minmax(0,1.18fr) minmax(310px,.82fr);gap:14px;margin-bottom:14px}.layout-wide{margin-bottom:14px}.analytics-panel{padding:20px}.analytics-panel h2{margin:0;color:#17213d;font-size:1.15rem;letter-spacing:-.025em}.panel-kicker{margin:0 0 6px;color:#6874c7;font-size:10px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.panel-copy{margin:7px 0 17px;color:#7b8599;font-size:12px;line-height:1.5}.panel-header{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:16px}.panel-header .panel-copy{margin-bottom:0}.subtle-badge{padding:5px 8px;border-radius:8px;color:#5a67bc;background:#eef0ff;font-size:10px;font-weight:700;white-space:nowrap}
.funnel-list{display:grid;gap:13px}.funnel-row{display:grid;grid-template-columns:150px minmax(90px,1fr) 52px;align-items:center;gap:12px;font-size:12px}.funnel-label{color:#4f5b75}.bar-track{height:10px;overflow:hidden;border-radius:99px;background:#edf0f6}.bar-value{height:100%;border-radius:inherit;background:linear-gradient(90deg,#5268ce,#61b8d4)}.funnel-value{text-align:right;color:#17213d;font-size:12px;font-weight:750}.funnel-meta{grid-column:2 / 4;margin-top:-8px;color:#8992a5;font-size:10px}.funnel-meta strong{color:#5866ba}.conversion-pill{color:#5260b8}
.chart-bars{display:grid;align-items:end;grid-template-columns:repeat(auto-fit,minmax(28px,1fr));gap:7px;min-height:160px;padding:12px 0 0;border-bottom:1px solid #e5e8f0}.day-bar{display:grid;grid-template-rows:1fr auto;gap:7px;height:146px;min-width:0}.day-bar-fill{align-self:end;min-height:3px;border-radius:6px 6px 0 0;background:#7184d6}.day-bar span{overflow:hidden;color:#8992a5;font-size:9px;text-align:center;text-overflow:ellipsis;white-space:nowrap}.empty-chart{display:grid;place-items:center;min-height:160px;color:#8b94a7;font-size:12px}
.audience-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.segment-list{display:grid;gap:11px}.segment-row{display:grid;grid-template-columns:minmax(0,1fr) 38px;gap:10px}.segment-name{overflow:hidden;color:#4f5b75;font-size:12px;text-overflow:ellipsis;white-space:nowrap}.segment-bar{height:7px;margin-top:5px;overflow:hidden;border-radius:99px;background:#edf0f6}.segment-bar i{display:block;height:100%;border-radius:inherit;background:#a8a7dc}.segment-count{color:#17213d;font-size:12px;font-weight:750;text-align:right}.empty-state{padding:18px 0;color:#8992a5;font-size:12px;line-height:1.5}
.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:12px}caption{padding:0 0 10px;color:#6874c7;font-size:10px;font-weight:800;letter-spacing:.1em;text-align:left;text-transform:uppercase}th,td{padding:10px 8px;border-bottom:1px solid #edf0f5;text-align:left;vertical-align:top}th{color:#7c879c;font-size:10px;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}td{color:#56627a}td strong{display:block;max-width:360px;overflow:hidden;color:#1b2748;font-weight:700;text-overflow:ellipsis;white-space:nowrap}td small{display:block;margin-top:3px;color:#9aa2b2;font-size:10px}.number-cell{color:#1b2748;font-weight:700;white-space:nowrap}.muted{color:#8a93a6}.empty-table{text-align:center}
.report-performance-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:10px}.report-stat{padding:13px;border:1px solid #e4e7ef;border-radius:11px;background:#fafbfe}.report-stat span{display:block;color:#7b8599;font-size:10px;line-height:1.3}.report-stat strong{display:block;margin-top:7px;color:#17213d;font-size:1.25rem;letter-spacing:-.03em}.health-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.health-item{padding:13px;border:1px solid #e4e7ef;border-radius:11px;background:#fafbfe}.health-item strong{display:block;color:#17213d;font-size:1.15rem}.health-item span{display:block;margin-top:5px;color:#7d879a;font-size:11px;line-height:1.35}.activity-table time{color:#8a93a6;white-space:nowrap}.status-panel{display:grid;place-items:center;min-height:55vh;text-align:center}.status-panel h1{margin:10px 0 7px;color:#17213d;font-size:1.8rem}.status-panel p{max-width:420px;margin:0;color:#748098;font-size:13px;line-height:1.5}.status-panel button{margin-top:18px;padding:10px 14px;border:1px solid #dbe0ed;border-radius:10px;color:#fff;background:#4b5cc1;cursor:pointer}
.export-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.export-button{padding:9px 11px;border:1px solid #dbe0ed;border-radius:9px;color:#4b5cc1;background:#fff;cursor:pointer;font-size:11px;font-weight:700}.export-button:hover,.export-button:focus-visible{border-color:#6d7cdb;outline:3px solid rgba(88,104,201,.16)}
.analytics-panel:has(#health-heading){align-self:start}.activity-table{table-layout:fixed}.activity-table th:first-child,.activity-table td:first-child{width:70%;overflow-wrap:anywhere}.activity-table th:last-child,.activity-table td:last-child{width:30%}.activity-table time{font-size:10px;white-space:nowrap}
@media(max-width:1080px){.metric-grid{grid-template-columns:repeat(3,1fr)}.report-performance-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:820px){.analytics-shell{width:min(100% - 28px,1340px);padding-top:20px}.dashboard-header-row{align-items:flex-start;flex-direction:column}.dashboard-controls{justify-content:flex-start}.layout-two{grid-template-columns:1fr}.health-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:540px){.metric-grid{grid-template-columns:1fr 1fr;gap:8px}.metric-card{min-height:100px;padding:13px}.metric-value{font-size:1.5rem}.analytics-panel{padding:16px}.funnel-row{grid-template-columns:105px minmax(60px,1fr) 40px;gap:8px}.funnel-meta{grid-column:2 / 4}.audience-grid{grid-template-columns:1fr}.report-performance-grid,.health-grid{grid-template-columns:1fr 1fr}.dashboard-controls select,.dashboard-controls input{max-width:140px}.range-group{width:100%;justify-content:space-between}.range-group button{flex:1;padding:0 5px}.table-wrap{margin-right:-4px}.analytics-panel h2{font-size:1.05rem}}
`;

function escape(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character); }
function number(value: number): string { return new Intl.NumberFormat('en-GB').format(value); }
function pct(value: number | null): string { return value === null ? 'Unavailable' : `${value.toFixed(1)}%`; }
function publisherLabel(report: AnalyticsReport & { publisherName?: string }): string { return report.publisherName || report.publisherId.replace(/[-_]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function selectedRange(range?: AnalyticsDateRange): '7d' | '30d' | '90d' | 'all' {
  if (!range) return 'all';
  const days = Math.round((Date.parse(range.to) - Date.parse(range.from)) / 86_400_000) + 1;
  return days >= 90 ? '90d' : days >= 30 ? '30d' : '7d';
}
function dateInputValue(value?: string): string { return value?.slice(0, 10) ?? ''; }
function table(headers: string[], rows: string[][], empty: string, caption: string, className = ''): string { const tableClass = className || (caption === 'Recent activity' ? 'activity-table' : ''); return `<div class="table-wrap"><table class="${escape(tableClass)}"><caption>${escape(caption)}</caption><thead><tr>${headers.map((header) => `<th scope="col">${escape(header)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${headers.length}" class="empty-table muted">${escape(empty)}</td></tr>`}</tbody></table></div>`; }
function metricCard(label: string, value: number, note: string): string { return `<article class="metric-card"><div class="metric-label">${escape(label)}</div><p class="metric-value">${number(value)}</p><p class="metric-note">${escape(note)}</p></article>`; }
function unavailable(value: number | null): string { return value === null ? 'Unavailable' : pct(value); }

function reportMarkup(report: AnalyticsReport & { publisherName?: string }, admin: boolean, internal?: InternalAnalyticsAggregate, sample = false): string {
  const maxDay = Math.max(1, ...report.daily.map((day) => day.impressions));
  const maxIndustry = Math.max(1, ...report.audience.industries.map((item) => item.count));
  const maxRole = Math.max(1, ...report.audience.roleFunctions.map((item) => item.count));
  const articleRows = report.content.topStories.map((item) => [`<strong title="${escape(item.title)}">${escape(item.title)}</strong><small>${escape(item.articleId)}</small>`, escape(item.category), `<span class="number-cell">${number(item.impressions)}</span>`, `<span class="number-cell">${number(item.clicks)}</span>`, `<span class="number-cell">${pct(item.ctr)}</span>`, `<span class="number-cell">${number(item.reportCount)}</span>`]);
  const clickedRows = report.content.topClickedStories.map((item) => [`<strong title="${escape(item.title)}">${escape(item.title)}</strong><small>${escape(item.articleId)}</small>`, escape(item.category), `<span class="number-cell">${number(item.impressions)}</span>`, `<span class="number-cell">${number(item.clicks)}</span>`, `<span class="number-cell">${pct(item.ctr)}</span>`]);
  const recentRows = report.recentActivity.map((item) => [escape(item.context), `<time datetime="${escape(item.timestamp)}">${escape(new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'UTC' }).format(new Date(item.timestamp)))} UTC</time>`]);
  const sampleNotice = sample ? '<div class="subtle-badge" role="status">Sample data</div>' : '';
  const funnelMarkup = report.funnel.map((item) => `<div class="funnel-row"><span class="funnel-label">${escape(item.stage)}</span><div class="bar-track"><div class="bar-value" style="width:${item.percentage}%"></div></div><strong class="funnel-value">${number(item.count)}</strong><span class="funnel-meta">${item.conversionFromPrevious === null ? 'Entry stage' : `<strong>${pct(item.conversionFromPrevious)}</strong> from previous stage · ${pct(item.conversionFromFirst)} of impressions`}</span></div>`).join('');
  const segmentMarkup = (items: AnalyticsReport['audience']['industries'], max: number, empty: string) => items.length ? `<div class="segment-list">${items.map((item) => `<div class="segment-row"><div><div class="segment-name" title="${escape(item.label)}">${escape(item.label)}</div><div class="segment-bar"><i style="width:${item.count / max * 100}%"></i></div></div><span class="segment-count">${number(item.count)}</span></div>`).join('')}</div>` : `<p class="empty-state">${escape(empty)}</p>`;
  const ai = report.generationHealth;
  const activeRange = selectedRange(report.range);
  return `<div class="analytics-app"><style>${dashboardStyles}</style><main class="analytics-shell">
    <header class="dashboard-header"><div class="publisher-line"><span class="publisher-mark" aria-hidden="true">PI</span><span>${escape(publisherLabel(report))}</span>${sampleNotice}</div><div class="dashboard-header-row"><div><p class="dashboard-eyebrow">Publisher intelligence</p><h1>Briefing analytics</h1><p class="dashboard-subtitle">See who is using the briefing, where the journey completes, and which stories earn attention.</p></div><div class="dashboard-controls"><span class="muted">Current publisher</span><strong>${escape(publisherLabel(report))}</strong><div class="range-group" role="group" aria-label="Date range"><button class="range-button ${activeRange === '7d' ? 'active' : ''}" data-range="7d">7 days</button><button class="range-button ${activeRange === '30d' ? 'active' : ''}" data-range="30d">30 days</button><button class="range-button ${activeRange === '90d' ? 'active' : ''}" data-range="90d">90 days</button><button class="range-button ${activeRange === 'all' ? 'active' : ''}" data-range="all">All time</button></div><button class="refresh-button" type="button" data-refresh>Refresh</button></div></div><p class="updated-label">UTC · ${report.range ? `${escape(dateInputValue(report.range.from))} to ${escape(dateInputValue(report.range.to))}` : 'all recorded analytics'}</p></header>
    <section class="metric-grid" aria-label="Key publisher metrics">${metricCard('Widget impressions', report.overview.widgetImpressions, 'Unique sessions that saw the widget')}${metricCard('Briefings requested', report.overview.briefingsRequested, 'Professional context submitted')}${metricCard('Reports generated', report.overview.reportsGenerated, 'Completed briefing reports')}${metricCard('Reports viewed', report.overview.reportsViewed, `${pct(report.reportPerformance.viewRate)} report view rate`)}${metricCard('Story clicks', report.overview.storyClicks, `${pct(report.overview.searchToClickRate)} click rate per generated report`)}${metricCard('Report shares', report.overview.reportShares, 'Recorded share actions')}</section>
    <div class="layout-two"><section class="analytics-panel" aria-labelledby="funnel-heading"><div class="panel-header"><div><p class="panel-kicker">Conversion</p><h2 id="funnel-heading">Briefing funnel</h2><p class="panel-copy">Unique tenant-scoped sessions at each professional journey stage.</p></div><span class="subtle-badge">Drop-off at a glance</span></div><div class="funnel-list" aria-label="Briefing funnel stages">${funnelMarkup}</div></section><section class="analytics-panel" aria-labelledby="usage-heading"><p class="panel-kicker">Reach</p><h2 id="usage-heading">Usage over time</h2><p class="panel-copy">Daily widget impressions in the selected UTC range.</p>${report.daily.length ? `<div class="chart-bars" role="img" aria-label="Daily widget impressions chart">${report.daily.map((day) => `<div class="day-bar" title="${escape(day.date)}: ${day.impressions} impressions"><div class="day-bar-fill" style="height:${Math.max(3, day.impressions / maxDay * 100)}%"></div><span>${escape(day.date.slice(5))}</span></div>`).join('')}</div>` : '<div class="empty-chart">No impressions recorded in this period.</div>'}</section></div>
    <section class="analytics-panel layout-wide" aria-labelledby="audience-heading"><div class="panel-header"><div><p class="panel-kicker">Audience</p><h2 id="audience-heading">Who is using the briefing?</h2><p class="panel-copy">Normalised professional categories from completed company and role analysis. Raw company URLs and job titles are not stored in analytics.</p></div></div><div class="audience-grid"><div><h3>Industries</h3>${segmentMarkup(report.audience.industries, maxIndustry, 'No categorised industry data recorded in this period.')}</div><div><h3>Role functions</h3>${segmentMarkup(report.audience.roleFunctions, maxRole, 'No categorised role-function data recorded in this period.')}</div></div></section>
    <section class="analytics-panel layout-wide" aria-labelledby="content-heading"><div class="panel-header"><div><p class="panel-kicker">Content performance</p><h2 id="content-heading">Which stories drive engagement?</h2><p class="panel-copy">Titles and IDs come from story impression metadata already captured by the publisher experience.</p></div></div>${table(['Story', 'Category', 'Impressions', 'Clicks', 'CTR', 'Reports'], articleRows, 'No article impressions recorded in this period.', 'Top stories by impressions')}<div style="height:18px"></div>${table(['Story', 'Category', 'Impressions', 'Clicks', 'CTR'], clickedRows, 'No article clicks recorded in this period.', 'Top clicked stories')}<div class="export-row"><button class="export-button" data-export="recommended" type="button">Export story performance</button><button class="export-button" data-export="clicked" type="button">Export clicked stories</button></div></section>
    <section class="analytics-panel layout-wide" aria-labelledby="report-heading"><div class="panel-header"><div><p class="panel-kicker">Report performance</p><h2 id="report-heading">From generation to return visits</h2></div></div><div class="report-performance-grid"><div class="report-stat"><span>Reports generated</span><strong>${number(report.reportPerformance.generated)}</strong></div><div class="report-stat"><span>Reports viewed</span><strong>${number(report.reportPerformance.viewed)}</strong></div><div class="report-stat"><span>View rate</span><strong>${pct(report.reportPerformance.viewRate)}</strong></div><div class="report-stat"><span>Shares</span><strong>${number(report.reportPerformance.shared)}</strong></div><div class="report-stat"><span>Profile edits</span><strong>${number(report.reportPerformance.edited)}</strong></div><div class="report-stat"><span>Clicks / viewed report</span><strong>${report.reportPerformance.averageStoryClicksPerViewedReport === null ? 'Unavailable' : report.reportPerformance.averageStoryClicksPerViewedReport.toFixed(1)}</strong></div><div class="report-stat"><span>Impressions / viewed report</span><strong>${report.reportPerformance.averageStoryImpressionsPerViewedReport === null ? 'Unavailable' : report.reportPerformance.averageStoryImpressionsPerViewedReport.toFixed(1)}</strong></div></div></section>
    <div class="layout-two"><section class="analytics-panel" aria-labelledby="health-heading"><div class="panel-header"><div><p class="panel-kicker">Operational signal</p><h2 id="health-heading">AI & generation health</h2><p class="panel-copy">Usage flags are shown only when explicitly persisted by the generation flow.</p></div></div><div class="health-grid"><div class="health-item"><strong>${pct(ai.generationSuccessRate)}</strong><span>Successful generations</span></div><div class="health-item"><strong>${unavailable(ai.aiProfileUsageRate)}</strong><span>AI profile usage</span></div><div class="health-item"><strong>${unavailable(ai.aiRerankUsageRate)}</strong><span>AI rerank usage</span></div><div class="health-item"><strong>${unavailable(ai.aiExplanationUsageRate)}</strong><span>AI explanation usage</span></div><div class="health-item"><strong>${unavailable(ai.deterministicProfileRate)}</strong><span>Deterministic profile fallback</span></div><div class="health-item"><strong>${ai.generationFailures === null ? 'Unavailable' : number(ai.generationFailures)}</strong><span>Recorded generation failures</span></div></div></section><section class="analytics-panel" aria-labelledby="activity-heading"><div class="panel-header"><div><p class="panel-kicker">Latest signals</p><h2 id="activity-heading">Recent activity</h2></div></div>${table(['Event', 'UTC time'], recentRows, 'No report or story activity recorded in this period.', 'Recent activity')}</section></div>
    ${admin && internal ? `<section class="analytics-panel" style="margin-top:14px"><p class="panel-kicker">Development only</p><h2>Internal aggregate</h2><p class="panel-copy">Cross-publisher totals remain available only in explicit development/admin mode.</p><p class="muted">${number(internal.publisherCount)} publishers · ${number(internal.totalSearches)} reports generated · ${number(internal.totalClicks)} story clicks</p></section>` : ''}
  </main></div>`;
}

function loadingMarkup(): string { return `<div class="analytics-app"><style>${dashboardStyles}</style><main class="analytics-shell status-panel"><div><p class="dashboard-eyebrow">Publisher intelligence</p><h1>Loading briefing analytics</h1><p>Preparing the selected publisher view.</p></div></main></div>`; }
function errorMarkup(): string { return `<div class="analytics-app"><style>${dashboardStyles}</style><main class="analytics-shell status-panel"><div><p class="dashboard-eyebrow">Publisher intelligence</p><h1>Analytics are temporarily unavailable</h1><p>We could not load this publisher’s analytics for the selected period. Please try again.</p><button type="button" data-dashboard-retry>Try again</button></div></main></div>`; }

async function fetchReport(publisherId: string, range?: AnalyticsDateRange): Promise<AnalyticsReport & { publisherName?: string }> {
  const query = range ? `?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}` : '';
  const response = await fetch(`/api/analytics/${encodeURIComponent(publisherId)}/overview${query}`);
  if (!response.ok) throw new Error(`analytics_http_${response.status}`);
  const report = await response.json() as AnalyticsReport & { publisherName?: string };
  if (!report || report.publisherId !== publisherId || !report.overview) throw new Error('analytics_invalid_response');
  return report;
}

export async function renderAnalyticsDashboard(root: HTMLElement, store?: AnalyticsStore): Promise<void> {
  const params = new URLSearchParams(window.location.search);
  const seedData = store === undefined && params.get('sample') === '1';
  const analyticsStore = store ?? (seedData ? await createSeedAnalyticsStore() : undefined);
  let publisherId = params.get('publisher') ?? 'demo';
  const clock = seedData || store ? new Date('2026-09-28T12:00:00.000Z') : new Date();
  let range: AnalyticsDateRange | undefined = dateRangeForPreset('30d', clock);
  const admin = params.get('admin') === '1';
  const render = async () => {
    root.innerHTML = loadingMarkup();
    try {
      let report: AnalyticsReport & { publisherName?: string };
      let internal: InternalAnalyticsAggregate | undefined;
      if (analyticsStore) {
        const events = await analyticsStore.query({ publisherId, range });
        report = { ...buildAnalyticsReport(events, publisherId, range), publisherName: createPublisherRegistry().get(publisherId)?.manifest?.name };
        if (admin) {
          const ids = await analyticsStore.listPublisherIds();
          const reports = await Promise.all(ids.map(async (id) => buildAnalyticsReport(await analyticsStore.query({ publisherId: id, range }), id, range)));
          internal = buildInternalAnalyticsAggregate(reports);
        }
      } else {
        report = await fetchReport(publisherId, range);
      }
      root.innerHTML = reportMarkup(report, admin, internal, seedData);
      root.querySelectorAll<HTMLButtonElement>('[data-range]').forEach((button) => button.addEventListener('click', () => {
        const selected = button.dataset.range;
        range = selected === 'all' ? undefined : dateRangeForPreset(selected === '90d' ? '90d' : selected as '7d' | '30d', clock);
        void render();
      }));
      root.querySelector<HTMLButtonElement>('[data-refresh]')?.addEventListener('click', () => { void render(); });
      root.querySelectorAll<HTMLButtonElement>('[data-export]').forEach((button) => button.addEventListener('click', () => downloadReportCsv(report, button.dataset.export as AnalyticsExportKind)));
    } catch (error) {
      if (import.meta.env.DEV && typeof console !== 'undefined') console.warn('[publisher-analytics] dashboard request failed', { error: error instanceof Error ? error.name : 'unknown' });
      root.innerHTML = errorMarkup();
      root.querySelector<HTMLButtonElement>('[data-dashboard-retry]')?.addEventListener('click', () => { void render(); });
    }
  };
  await render();
}
